### PR TITLE
Material Theme templates

### PR DESCRIPTION
**Pull request by re1**
### Introduction

The fork extends the existing template by adding two additional configurations for both Material themes and Material Theme accent colors. The [Material Theme](https://github.com/ChrisRM/material-theme-jetbrains) plugin is quite common among JetBrains users and supports limited custom themes which can also be styled through settings.

### Changes

* Material themes can now be imported as `.jar` files and include their editor scheme too
* Repository structure and build file got a cleanup
* `README.md` is now easier to understand while also giving more information on where to import and or store files
* Some dev is now going to get some slee... :zzz:

### CODE REVIEW

**Comment by re1** [comment]
Travis CI checks only fail due to the absence of a `Rakefile` which is not part of the project. You might want to adjust your build configuration to

1. clone the ruby builder
``` sh
git clone https://github.com/obahareth/base16-builder-ruby.git builder
```
2. copy the contents of the `templates` folder into `builder/templates/jetbrains`
``` sh
cp templates/* builder/templates/jetbrains
```
3. download dependencies and run the builder
``` sh
cd builder && bundle install && ./builder
```
4. copy the resulting files into the options folder
```sh
mkdir -p options
cp builder/out/options/* options
```
5. run the build script
``` sh
./build
```

Those steps could also be done using the `build` script found inside the repository but the ruby builder itself brings many dependencies and takes lots of time for a complete build.

**Comment by re1** [comment]
All steps required for a complete build have finally been moved into the `build` script. Cloning the builder can be skipped by passing any parameter to the script (like `build 1`). Build files could also be ignored by using a `.gitignore` file but adding one for pure contribution purposes might bloat the repository a little.

The test can now easily run by just executing `./build`.

**Comment by re1** [comment]
You might want to change the description of the project itself to **Base16 themes for JetBrains' IDEs - such as IntelliJ, PyCharm and Webstorm - and the Material Theme plugin** and add http://chriskempson.com/projects/base16 as project page.

**Comment by adilosa** [comment]
Awesome!! Thanks for the PR.

**Comment by re1** [comment]
Glad I could help :)

**Pull request merged**
